version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: robotdb
      MYSQL_USER: robotuser
      MYSQL_PASSWORD: robotpass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    command: ["/app/entrypoint.sh"]
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql+pymysql://robotuser:robotpass@db:3306/robotdb"
      SECRET_KEY: "dev_secret_change_me"
      ACCESS_TOKEN_EXPIRE_MINUTES: "60"
      DATABASE_HOST: db
      DATABASE_PORT: "3306"
    ports:
      - "8000:8000"
    volumes:
      - ./:/app:cached

volumes:
  db_data:
